---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(shiny)
library(bslib)

create_app_link <- function(mode = c("app", "editor"), header = TRUE) {
  mode <- match.arg(mode)
  
  app_code <- "NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OAFgAiUHsIgiArrQAEAHgC06gCYLu9Iiz0AFKAHM47EevWlapanHUBedULAAhIgA91AEEzAEkvXDt9Q2NTAAk4KD04RnYBCIh7Ax4Yxj0AZVok+hZU9Mzok1zfPQ5I+1IrTgASTlJWF1swYxr1EHViggBrS0YiFQg9bWJqIkZEdUtuIlaAd15yAF8vNLr1ADNqNT0sIhXbDPtLqAJHEm8VUlISTqfLSxcAfWM-cM8wABUiG8XOpfD8wDsLpd1NdbhB7o9nl5GHAYEQAG5wL7+X5eLCojGuMG-AjUBScdx-eiWbQGCDWRjbMrQmE3Wh3B5PCCdFGtWZY764sD4vko0E4vDqUnkyleanaTgqAgEOCcThM3b2WHs+GcpFgFSoAzkbHg3B-ACqRqg5HFZqlZLVsq6NNQjFoMAk212kOhTFKu2+5xZ6hWhVI3EpAEYAEzM6GOZyuDzkPykADyD1QD063w+rRtcA1UMuXjB-SINXCmvUhWdMFYgrwNemZNQnAYII8-ywFoAovHLqTllB6F31D3+4P7KgZhmszmvLOiKRvSWlPYlEoRJxkpjGFpdHtxmznnxs6RzWNSBfzbu1TqBL1IteL01l6RD+oURNkmY5+wIC7CiACO7AAITng8TQNt8TStmgu56BulwfuwjAQLMMDsDGAAMuECChGwoS+C6kE0eYFraOjfhQSSMP8cBpoBuxUa4NG0Hs6jsFB5Gwf48FENQbZIU+XgIe2cB6F46hwNQu5-CeQkiVJXi7KgCjkJ0ACyrAVgEtDqpKbFESRFxEFIe5wH2mJkDxEBvq87wCv45pASWhrGnAYKdPx9raiQzpOS4a72MRkQvpZjCYjZFCkPZb4omimKmm5uyeYWPleH5vwBRkHjIgSmKheo4UXJFu7RdZtnxbxTS8k8KKpc+HnWuQWVgDlkp5c6DX8iVZX2BVVmxXZdUZSa3xpa1XlZSWQ2dY2ErmjWPUFQabVFpKNZEKgcIUh4dCtMGIYOE447cDGnQAHJwCsZ1Jr8WRGJUejeIk1jsFG5rTLMzpuh6XoQr6p1USoB1-HSDK4vNlycEJhTxIkySUpOA41vYYZ6BGlLSDWKGbpEg2eOZUUxTVCXQX5TTooZnZwNN0ISUhX6cdxdXU8zUliYQymIapYCyfJrheEpwn89JYC7LTHZjuxuhs5TfFLX4NN03LPMy-TMlyQpXi8HoSTKFLJbwGqVjy+oGmtDYXi6fptZGT9fOSXoK0oBMvxaxrrFLCs10rpxtAEDaOrsGbnAW+abSoMmfwrCwEB8JYT0qMwcLRqZIhbMoEA8HwrCBOg7BqHeVmMEoYAbLg4DQPAVCyH2eQAMJYCEZj-CE6bXXgvNkHFVD-OdcDzPEwlEOoeS8Pw4EiIEDxLHM6jyLTejqAA4swEAAFYkBgc8L7MFqMNQ8zcI8qCIAA9Ff7r94wezXHAGDEDAIgADLBxQu7zNpIT-CIWQhlZxQFYNpSsI9J5+xDruEQ-xGjzGsI8ZOCoGiMHINJCA-xWCx3mFPAuIgq410gLABAyB8SJHgBgGAehe7EH7pQZA-xeAUkMjCDIY8ZjqAAOqzGoGvfB-AYToH3hAKuABdIAA"
  
  app_url <- sprintf(
    "https://shinylive.rinterface.com/%s/#code=%s", mode, app_code
  )
  
  if (!header) {
    app_url <- paste0(app_url, "&h=0")
  }
  
  tags$iframe(
    # To allow the content to fill the full screen card
    class = "html-fill-item",
    src = app_url, 
    height = "700", 
    width = "100%",
    style = "border: 1px solid rgba(0,0,0,0.175); border-radius: .375rem;",
    allowfullscreen = "",
    allow = "autoplay",
    `data-external` = "1"
  )
}
```

# shinylivePkgDown

<!-- badges: start -->
<!-- badges: end -->

## Embedded app

Below is an embedded R shinylive app running in a separate server. The iframe is included in a `{bslib}` card. 

```{r, eval=TRUE, echo=FALSE}
card(create_app_link("app", FALSE), full_screen = TRUE)
```

## Embedded app + editor

An embedded shinylive app editor. User can share the code. Note: the plot won't likely show on smaller screen leading to an error in the R console.

```{r, eval=TRUE, echo=FALSE}
card(create_app_link("editor"), full_screen = TRUE)
```
